name: Deploy Vue App

on:
  push:
    branches: [master]
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      contents: read

    steps:
      - name: Force Fresh Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures clean state

      - name: Purge Action Caches
        run: |
          sudo rm -rf $RUNNER_TOOL_CACHE/*
          sudo rm -rf $AGENT_TOOLSDIRECTORY/*

      - name: Setup Node (with clean cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install Dependencies
        run: npm ci --no-audit --prefer-offline

      - name: Build Application
        run: npm run build

      - name: Upload Pages Artifact (Fresh Install)
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'dist'
          retention-days: 1  # Preces storage issues

      - name: Deploy Pages
        uses: actions/deploy-pages@v3
        timeout-minutes: 5